blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('<str:lang>', PostListView.as_view(), name='posts'),
    path('article/<slug:slug>/', PostDetailView.as_view(), name='post_ru'),
    path('article/<str:lang>/<slug:slug>', PostDetailView.as_view(), name='post'),
    path('', PostListView.as_view(), name='posts_ru'),
]

products/urls.py
from django.conf.urls import url
from .views import *
from django.urls.conf import path

app_name = 'products'
urlpatterns = [
    path('multiomega', MultiOmegaDetailView.as_view(), name="multiomega_ru"),
    path('<str:lang>/multiomega', MultiOmegaDetailView.as_view(), name="multiomega"),
    path('<str:lang>/multiomega.html', LangRedirect.as_view(pattern_name='products:multiomega', permanent=True)),
    path('multiomega.html', RedirectView.as_view(pattern_name='products:multiomega_ru', permanent=True)),

    path('multivitamin', MultiVitaminDetailView.as_view(), name="multivitamin_ru"),
    path('<str:lang>/multivitamin', MultiVitaminDetailView.as_view(), name="multivitamin"),
    path('<str:lang>/multivitamine.html', LangRedirect.as_view(pattern_name='products:multivitamin', permanent=True)),
    path('multivitamine.html', RedirectView.as_view(pattern_name='products:multivitamin_ru', permanent=True)),

    path('vitaminc', VitaminCDetailView.as_view(), name="vitaminc_ru"),
    path('<str:lang>/vitaminc', VitaminCDetailView.as_view(), name="vitaminc"),
    path('<str:lang>/vitamine-c.html', LangRedirect.as_view(pattern_name='products:vitaminc', permanent=True)),
    path('vitamine-c.html', RedirectView.as_view(pattern_name='products:vitaminc_ru', permanent=True)),

    path('ukachivanie', UkachivanieDetailView.as_view(), name="ukachivanie_ru"),
    path('<str:lang>/ukachivanie', UkachivanieDetailView.as_view(), name="ukachivanie"),
    path('<str:lang>/ukachivanie.html', LangRedirect.as_view(pattern_name='products:ukachivanie', permanent=True)),
    path('ukachivanie.html', RedirectView.as_view(pattern_name='products:ukachivanie_ru', permanent=True)),

    path('jeleyki', JeleykiDetailView.as_view(), name="jeleyki_ru"),
    path('<str:lang>/jeleyki', JeleykiDetailView.as_view(), name="jeleyki"),
    path('<str:lang>/jeleyki.html', LangRedirect.as_view(pattern_name='products:jeleyki', permanent=True)),
    path('jeleyki.html', RedirectView.as_view(pattern_name='products:jeleyki_ru', permanent=True)),

    path('shipuchie', ShipuchieaDetailView.as_view(), name="shipuchie_ru"),
    path('<str:lang>/shipuchie', ShipuchieaDetailView.as_view(), name="shipuchie"),
    path('<str:lang>/shipuchie.html', LangRedirect.as_view(pattern_name='products:shipuchie', permanent=True)),
    path('shipuchie.html', RedirectView.as_view(pattern_name='products:shipuchie_ru', permanent=True)),

    path('nabor', NaborDetailView.as_view(), name="nabor_ru"),
    path('<str:lang>/nabor', NaborDetailView.as_view(), name="nabor"),
    path('<str:lang>/nabor.html', LangRedirect.as_view(pattern_name='products:nabor', permanent=True)),
    path('nabor.html', RedirectView.as_view(pattern_name='products:nabor_ru', permanent=True)),

    path('akcia', AkciaView.as_view(), name="akcia_ru"),
    path('<str:lang>/akcia', AkciaView.as_view(), name="akcia"),
    path('<str:lang>/akcia.html', LangRedirect.as_view(pattern_name='products:akcia', permanent=True)),
    path('akcia.html', RedirectView.as_view(pattern_name='products:akcia_ru', permanent=True)),

    # general & ajax
    path('ditochkam', DitochkamView.as_view(), name="ditochkam_ru"),
    path('<str:lang>/ditochkam', DitochkamView.as_view(), name="ditochkam"),
    path('<str:lang>/ditochkam.html', LangRedirect.as_view(pattern_name='products:ditochkam', permanent=True)),
    path('ditochkam.html', RedirectView.as_view(pattern_name='products:ditochkam_ru', permanent=True)),


    path('list/', list_ajax, name='ajax'),
    path('uk/', GeneralView.as_view(), kwargs={'lang': 'uk'}, name='general_uk'),
    path('en/', GeneralView.as_view(), kwargs={'lang': 'en'}, name='general_en'),
    path('uk/index.html', RedirectView.as_view(pattern_name='products:general_uk'), kwargs={'lang': 'uk'}),
    path('en/index.html', RedirectView.as_view(pattern_name='products:general_en'), kwargs={'lang': 'en'}),
    path('<str:lang>/list/', list_ajax, name='ajax'),
    url(r'^$', GeneralView.as_view(), name='general'),
]

vitatone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT#, STATIC_URL, STATIC_ROOT

urlpatterns = [
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
] + static(MEDIA_URL, document_root=MEDIA_ROOT) #+ static(STATIC_URL, document_root=MEDIA_URL)

products/forms.py
from django import forms
from django.forms.models import BaseInlineFormSet
from ckeditor.widgets import CKEditorWidget
from .models import *


class LanguageReadOnlyMetaMixin():
    widgets = {
        'language': forms.TextInput(
            attrs={'readonly': 'readonly', 'style': 'border-color:white;'}
        ),
        'product': forms.TextInput(
            attrs={'readonly': 'readonly', 'style': 'border-color:white;display:none;'}
        )
    }


class ProductBodyModelForm(forms.ModelForm):

    class Meta:
        model = ProductBody
        fields = ["language", "name", "general_text", "title", "description", "keywords"]
        widgets = {
            'language': forms.TextInput(
                attrs={'readonly': 'readonly', 'style': 'border-color:white;'}
            )
        }


class ProductBodyInlineFormSet(BaseInlineFormSet):

    def __init__(self, *args, **kwargs):
        kwargs['initial'] = [{'language': x[0]} for x in ProductBody.languages]
        self.can_delete = False
        super(ProductBodyInlineFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


class MultiOmegaModelForm(forms.ModelForm):
    popup = forms.CharField(widget=CKEditorWidget())
    text = forms.CharField(widget=CKEditorWidget(config_name='off-p'))

    class Meta(LanguageReadOnlyMetaMixin):
        model = MultiOmega
        fields = ["language", "product", "products", "posts", "popup", "text", "link"]


class MultiVitaminModelForm(forms.ModelForm):
    popup = forms.CharField(widget=CKEditorWidget())

    class Meta(LanguageReadOnlyMetaMixin):
        model = MultiVitamin
        fields = ["language", "product", "popup", "link"]


class VitaminCModelForm(forms.ModelForm):
    popup = forms.CharField(widget=CKEditorWidget())

    text1 = forms.CharField(widget=CKEditorWidget())
    text2 = forms.CharField(widget=CKEditorWidget())

    class Meta(LanguageReadOnlyMetaMixin):
        model = VitaminC
        fields = ["language", "product", "popup", "text1", "text2", "link"]


class UkachivanieModelForm(forms.ModelForm):
    popup = forms.CharField(widget=CKEditorWidget())
    text = forms.CharField(widget=CKEditorWidget())

    class Meta(LanguageReadOnlyMetaMixin):
        model = Ukachivanie
        fields = ["language", "product", "popup", "text", "link"]



class JeleykiModelForm(forms.ModelForm):

    class Meta(LanguageReadOnlyMetaMixin):
        model = Jeleyki
        fields = ["language", "product", "text1", "text2"]


class ShipuchieModelForm(forms.ModelForm):
    popup = forms.CharField(widget=CKEditorWidget())

    class Meta(LanguageReadOnlyMetaMixin):
        model = Shipuchie
        fields = ["language", "product", "popup"]


class NaborModelForm(forms.ModelForm):

    class Meta(LanguageReadOnlyMetaMixin):
        model = Nabor
        fields = ["language", "product", "link"]

products/views.py
from django.views.generic import DetailView, TemplateView, RedirectView
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, Http404
from django.urls import reverse_lazy
from blog.models import PostBody
from general.models import GeneralProduct, General
from .models import *


class MultilangMixin():
    template_names = []

    def get_template_names(self):
        lang = self.kwargs.get('lang', 'ru')
        template = [name[1] for name in self.template_names if name[0] == lang]
        if len(template):
            return template
        else:
            raise Http404


class ProductMixin(MultilangMixin):

    def get_context_data(self, **kwargs):
        context = super(ProductMixin, self).get_context_data(**kwargs)

        if self.model is not None:
            lang = self.kwargs.get('lang', 'ru')
            context['item'] = get_object_or_404(self.model, language=lang)
        return context


class ProductPostMixin(ProductMixin):

    def get_context_data(self, **kwargs):
        context = super(ProductPostMixin, self).get_context_data(**kwargs)
        lang = self.kwargs.get('lang', 'ru')
        obj = context.get('item')
        if self.model == MultiOmega:
            obj = MultiOmega.objects.get(language='ru')
            context['posts'] = [x.postbody_set.get(language=lang) for x in obj.posts.all()[:3]]
        if self.model == Ditockam:
            obj = Ditockam.objects.get(language='ru')
        context['products'] = [x.productbody_set.get(language=lang) for x in obj.products.all()[:3]]
        return context



class MultiOmegaDetailView(ProductPostMixin, TemplateView):
    model = MultiOmega
    template_names = (
        ('ru', "multiomega/index.html"),
        ('en', "multiomega/index_en.html"),
        ('uk', "multiomega/index_uk.html")
    )


class MultiVitaminDetailView(ProductMixin, TemplateView):
    model = MultiVitamin
    template_names = (
        ('ru', "multivitamin/index.html"),
        ('en', "multivitamin/index_en.html"),
        ('uk', "multivitamin/index_uk.html")
    )


class VitaminCDetailView(ProductMixin, TemplateView):
    model = VitaminC
    template_names = (
        ('ru', "vitaminc/index.html"),
        ('en', "vitaminc/index_en.html"),
        ('uk', "vitaminc/index_uk.html")
    )


class UkachivanieDetailView(ProductMixin, TemplateView):
    model = Ukachivanie
    template_names = (
        ('ru', "ukachivanie/index.html"),
        ('en', "ukachivanie/index_en.html"),
        ('uk', "ukachivanie/index_uk.html")
    )


class JeleykiDetailView(ProductMixin, TemplateView):
    model = Jeleyki
    template_names = (
        ('ru', "jeleyki/index.html"),
        ('en', "jeleyki/index_en.html"),
        ('uk', "jeleyki/index_uk.html")
    )


class ShipuchieaDetailView(ProductMixin, TemplateView):
    model = Shipuchie
    template_names = (
        ('ru', "shipuchie/index.html"),
        ('en', "shipuchie/index_en.html"),
        ('uk', "shipuchie/index_uk.html")
    )


class NaborDetailView(ProductMixin, TemplateView):
    model = Nabor
    template_names = (
        ('ru', "nabor/index.html"),
        ('en', "nabor/index_en.html"),
        ('uk', "nabor/index_uk.html")
    )


class DitochkamView(ProductPostMixin, TemplateView):
    model = Ditockam

    template_names = (
        ('ru', "ditochkam/index.html"),
        ('en', "ditochkam/index_en.html"),
        ('uk', "ditochkam/index_uk.html")
    )


class GeneralView(MultilangMixin, TemplateView):

    template_names = (
        ('ru', "general/index.html"),
        ('en', "general/index_en.html"),
        ('uk', "general/index_uk.html")
    )

    def get_context_data(self, **kwargs):
        context = super(GeneralView, self).get_context_data(**kwargs)
        context['item'] = get_object_or_404(General, language=self.kwargs.get('lang', 'ru'))
        return context

class AkciaView(MultilangMixin, TemplateView):

    template_names = (
        ('ru', "akcia/index.html"),
        ('en', "akcia/index_en.html"),
        ('uk', "akcia/index_uk.html")
    )

    def get_context_data(self, **kwargs):
        context = super(AkciaView, self).get_context_data(**kwargs)
        context['link_nabor'] = Nabor.objects.first().link
        context['item'] = get_object_or_404(Akciya, language=self.kwargs.get('lang', 'ru'))
        return context


def list_ajax(req, lang='ru'):
    it = GeneralProduct.objects.first()
    items = it.child, it.adults, it.avitaminoz, it.hurt, it.beaty
    prods = ProductBody.objects.filter(language=lang)
    res = dict()
    for i, item in zip((1, 2, 6, 7, 8), items):
        l = []
        for x in item.all():
            prod = x.productbody_set.get(language=lang)
            d = {
                    "name": f"<span class='vitatone'>VITA<span>TONE</span></span> {prod.general_text}",
                    "src": x.image.url,
                    "caption": f"<span style='font-size: 1.2em'><span class='vitatone'>VITA<span>TONE</span></span> {prod.general_text}</span>",
                    "url": prod.get_absolute_url()
                }
            l.append(d)
        res[f'category{i}'] = l
    return JsonResponse(res)


class LangRedirect(RedirectView):
    def get_redirect_url(self, lang, *args, **kwargs):
        return reverse_lazy(self.pattern_name, kwargs={'lang': lang})

products/templates/includes/footer_menu_prods/index.html
<nav class="footer-menu">
                <ul>
                  <li><a href="{% url "products:general" %}">Главная</a></li>
                  <li class="active"><span>Продукты</span>
                    <ul>
                      <li><a href="{% url "products:multiomega_ru" %}">МультиОмега</a></li>
                      <li><a href="{% url "products:multivitamin_ru" %}">Леденцы Мультивитамин</a></li>
                      <li><a href="{% url "products:vitaminc_ru" %}">Леденцы с витамином С</a></li>
                      <li><a href="{% url "products:ukachivanie_ru" %}">Леденцы при укачивании и тошноте</a></li>
                      <li><a href="{% url "products:jeleyki_ru" %}">Желейные мультивитамины</a></li>
                      <li><a href="{% url "products:shipuchie_ru" %}">Шипучие мультивитамины</a></li>
                      <li><a href="{% url "products:nabor_ru" %}">Подарочный набор</a></li>
                    </ul>
                  </li>
                  <li><a href="{% url "blog:posts_ru" %}">Важно знать</a></li>
                  <li><a href="{% url "products:ditochkam_ru" %}">Деткам</a></li>
                  <li><a href="{% url "products:general" %}#our-contacts">Контакты</a></li>
                </ul>
              </nav>
<div class="copyright">
                <p>Все права защищены. При использовании материалов сайта <span>ссылка на сайт vitatone.ua обязательна. VITATONE 2017</span><span>© 2017 International Vitamin Corporation</span></p>
                <p class="made-in">Произведено в Польше по заказу и под контролем «NEWTONE PHARMA LIMITED», Великобритания</p>
              </div>

products/templates/includes/footer_menu_prods/index_en.html
<nav class="footer-menu">
                <ul>
                  <li><a href="{% url "products:general_en" %}">Main</a></li>
                  <li class="active"><span>Products</span>
                    <ul>
                      <li><a href="{% url "products:multiomega" "en" %}">MultiOmega</a></li>
                      <li><a href="{% url "products:multivitamin" "en" %}">Drops multivitamin</a></li>
                      <li><a href="{% url "products:vitaminc" "en" %}">Drops with Vitamin C</a></li>
                      <li><a href="{% url "products:ukachivanie" "en" %}">Drops for travel sickness and nausea</a></li>
                      <li><a href="{% url "products:jeleyki" "en" %}">Jelly multivitamin</a></li>
                      <li><a href="{% url "products:shipuchie" "en" %}">Effervescent multivitamin</a></li>
                      <li><a href="{% url "products:nabor" "en" %}">Gift set</a></li>
                    </ul>
                  </li>
                    <li>
                    <a href="{% url "blog:posts" "en" %}">Important</a>
                  </li>
                  <li><a href="{% url "products:ditochkam" "en" %}">For Children</a></li>
                  <li><a href="{% url "products:general_en" %}#our-contacts">Contacts</a></li>
                </ul>
              </nav>
<div class="copyright">
                <p>All rights reserved. When using site materials <span> link to vitatone.ua is mandatory. VITATONE 2017</span><span>© 2017 International Vitamin Corporation</span></p>
                <p class="made-in">Manufactured in Poland by order and under control of NEWTONE PHARMA LIMITED, Great Britain</p>
              </div>

products/templates/includes/footer_menu_prods/index_uk.html
            <nav class="footer-menu">
                <ul>
                  <li><a href="{% url "products:general_uk" %}">Головна</a></li>
                  <li class="menu-item-has-children active"><span>Продукти</span>
                    <ul>
                      <li><a href="{% url "products:multiomega" 'uk' %}">МультиОмега</a></li>
                      <li><a href="{% url "products:multivitamin" 'uk' %}">Льодяники Мультивітамін</a></li>
                      <li><a href="{% url "products:vitaminc" 'uk' %}">Льодяники з вітаміном С</a></li>
                      <li><a href="{% url "products:ukachivanie" 'uk' %}">Льодяники при захитуванні та нудоті</a></li>
                      <li><a href="{% url "products:jeleyki" 'uk' %}">Желейні мультивітаміни</a></li>
                      <li><a href="{% url "products:shipuchie" 'uk' %}">Шипучі мультивітаміни</a></li>
                      <li><a href="{% url "products:nabor" 'uk' %}">Подарунковий набір</a></li>
                    </ul>
                  </li>
                    <li><a href="{% url "blog:posts" "uk" %}">Важливо знати</a></li>
                  <li><a href="{% url "products:ditochkam" 'uk' %}">Діточкам</a></li>
                  <li><a href="{% url "products:general_uk" %}/#our-contacts">Контакти</a></li>
                </ul>
              </nav>
            <div class="copyright">
                <p>Всі права захищені. При використанні матеріалів сайту <span>посилання на сайт vitatone.ua обов’язкове. VITATONE 2017</span><span>© 2017 International Vitamin Corporation</span></p>
                <p class="made-in">Вироблено в Польщі на замовлення та під контролем «NEWTONE PHARMA LIMITED», Велика Британія</p>
              </div>